### ISSUE TITLE
specifying latest of `opsmgr_version` pull unlisted OpsMan version (as seen from Pivnet) 

### ISSUE THREAD

**Issue by jtarchie** [pivotal-cf/toolsmiths-shared-scripts#3]
Right now, if we use our user, and visit the [OpsMan product](https://network.pivotal.io/products/ops-manager) page, the latest version listed is 1.7.9.

When we specified `latest` for `opsmgr_version` in the `deploy-pcf-vsphere` pipeline, it managed to download the `pcf-vsphere-1.8-aplha1.ova` as the latest version.

We are using the correct API key associated with our account, so we don't know where it is getting that meta information.

**Comment by derwei** [comment]
Seems like this is a PivNet API issue where what you see via the API differs from what you see from the UI.
When I CURL the API with the token you gave me, I was able to see the 1.8-alpha1.
