### ISSUE TITLE
Azure storage account keys

### ISSUE THREAD

**Issue by mjj209** [pivotal-cf/toolsmiths-shared-scripts#4]
when I run the command:

azure storage account keys list --resource-group $resource_group_name $storage_account_name

I expect to get the azure storage key, but I receive the following output:
 2016-07-07 16:31:51 ☆ ruby 2.3.0p0 mjarvis in ~/workspace/deployments-toolsmiths/azure
± |master U:2 ✗| → azure storage account keys list --resource-group $resource_group_name $storage_account_name

  error: unknown option `--resource-group'

**Comment by markstokan** [comment]
We believe this is user error passing un-initiated bash variables ($resource_group_name and $storage_account_name).  We logged in and pulled the actual names of a valid resource group and valid storage account name and successfully listed the keys using the command...

azure storage account keys list --resource-group toolsmithstest toolsmithstestsa
