### ISSUE TITLE
Make Route 53 DNS name configurable in azure terraform script

### ISSUE THREAD

**Issue by joemoore** [pivotal-cf/toolsmiths-shared-scripts#8]
Inside azure.tf, the `azure` subdomain is hardcoded: https://github.com/pivotal-cf/toolsmiths-shared-scripts/blob/master/azure/azure.tf#L346-L364

Please make this configurable since some teams may not want it.

Thanks!

Joe and Brenda

**Comment by mjj209** [comment]
we're no longer supporting the azure deploy scripts.
